version: '3.4'

services:
  app:
    image: ticket-python-flask
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/ticket_python_flask

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_PASSWORD: password
